language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 90ed49a0936d5459bbcee64ac2de27a0a69bd123
 local_dir: dist
 on:
   branch: master